### PR TITLE
replace landscape.io with codacy

### PR DESCRIPTION
**Pull request by fyfe**
[landscape.io](https://landscape.io/github/modoboa/modoboa) hasn't worked since late 2017.  The only other free solution I've found is [codacy](https://www.codacy.com/).

I've added [my fork](https://www.codacy.com/app/fyfe/modoboa/dashboard) to codacy to try it out.

### CODE REVIEW

**Comment by fyfe** [comment]
Not sure why the codecov/project check fails, this commit doesn't touch anything that codecov checks.

**Comment by tonioo** [comment]
@fyfe Looks like codacy also do coverage?

**Comment by fyfe** [comment]
@tonioo It does, I've enabled it in the travis configuration but I haven't had time to check it out. It wouldn't do any harm using both for now.

**Comment by tonioo** [comment]
So, do I need to register something?

**Comment by fyfe** [comment]
Login to [codecy](https://www.codacy.co) using your GitHub account and then activate the repositories you want to use.

**Comment by kryskool** [comment]
Can you add a [.codecy.yml](https://support.codacy.com/hc/en-us/articles/115002130625-Codacy-Configuration-File) file, because test folder return false positive check 

capture d ecran 2018-04-07 a 10 25 38

Regards,

**Comment by kryskool** [comment]
@fyfe can you made the changes ?

Regards

**Comment by fyfe** [comment]
Codacy allows each warning/error to be reviewed and ignored if they are false positives, I rather do that than not check the test files.

image

**Pull request merged**
