### PR TITLE
Remove Python 2 support

### PR DESCRIPTION
**Pull request by jeromelebleu**
Python 2 support has ended yesterday - i.e. 2020-01-01... This drops Python 2.7 from Modoboa and update the code to move to Python 3 only:
* Update each dependency to the most recent version which doesn't require big changes - i.e. *Django* and *Django REST Framework* are not updated to the last release because of that
* Remove coding header and `__future__` imports
* Remove use of `six`
* In `setup.py`, remove use of `io.open`, add `python_requires` and update classifiers
* In README.rst, specify the Python 3 version support
* In `.travis.yml` and `tox.ini`, stop testing on Python 2
* In `setup.cfg`, remove `[bdist_wheel]` section

### CODE REVIEW

**Comment by jeromelebleu** [comment]
I had a look at the coverage decrease and I think it is probably a side effect of the `from __future__ import ...` and other lines removal.

**Comment by tonioo** [comment]
@jeromelebleu is this PR ready to merge?

**Comment by jeromelebleu** [comment]
Yes! #1818 may be merged first, but it doesn't really matter.

**Comment by tonioo** [comment]
@jeromelebleu Great. Thank you!

**Pull request merged**
