### PR TITLE
Update LoginForm.vue with Refactored Code

### PR DESCRIPTION
**Pull request by RJohnPaul**
Enhanced error handling for better user experience along with Optimized imports for better performance also Added aria-label attributes for better accessibility ,Improved the password visibility toggle for better usability and finally Made some minor UI improvements for better aesthetics.

### CODE REVIEW

**Comment by Spitfireap** [comment]
Hi, 
Thanks for the PR.
Sadly, we are going to remove the login form in vue and only use the one from Django in order to implement OIDC (#3217).
We do need to refresh the old login page a bit though if you up for it.

**Comment by RJohnPaul** [comment]
sure thanks

**Comment by RJohnPaul** [comment]
may i ask where is the old login page located?

**Comment by Spitfireap** [comment]
There it is ```modoboa/templates/registration/login.html```. Can you target #3238 ?

**Comment by RJohnPaul** [comment]
please check as i have implemented a few changes as requested

**Comment by tonioo** [comment]
@RJohnPaul We removed the LoginForm component from the frontend so your PR is now obsolete unfortunately. Thanks anyway :)

**Pull request closed without merging**
