### PR TITLE
WIP: Add Python 3.7 on CI Test

### PR DESCRIPTION
**Pull request by kryskool**
Description of the issue/feature this PR addresses:

Python 3.7 final release must be out in 2 months, It's time to test it
See: https://www.python.org/dev/peps/pep-0537/

Current behavior before PR:

Not revelant

Desired behavior after PR is merged:

Not revelant

### CODE REVIEW

**Comment by fyfe** [comment]
@kryskool gevent needs updated in `requirements.txt` for Py3.7, I'm not sure why it's pinned to 1.2.2.

**Comment by kryskool** [comment]
@fyfe 

Maybe because 1.2.2 is the last release version https://github.com/gevent/gevent/releases

For now i add matrix exclusion fail test

**Comment by kryskool** [comment]
It's seem Cython version is too old

**Comment by fyfe** [comment]
setuptools needs upgraded to fix the `ValueError: bad marshal data (unknown type code)` errors
```
  - if [ $TRAVIS_PYTHON_VERSION = 3.7-dev ]; then pip install -U "setuptools" ; fi
```
and `gevent` needs unpinned in `requirements.txt`, `pip install -r requirements.txt` is downgrading gevent to 1.2.2

---

These changes get the test suite running, but there are [issues with Django](https://code.djangoproject.com/ticket/28814) and I'm not sure if the fixes will be backported to Django 1.*; if we upgrade to Django 2.0 it means dropping support for Python 2.7.

**Comment by kryskool** [comment]
Now the problem seem relate to Django and Django rest framework
```
  File "<frozen importlib._bootstrap_external>", line 722, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/modoboa/modoboa/modoboa/urls.py", line 15, in <module>
    from rest_framework.documentation import include_docs_urls
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/rest_framework/documentation.py", line 6, in <module>
    from rest_framework.schemas import SchemaGenerator, get_schema_view
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/rest_framework/schemas/__init__.py", line 25, in <module>
    from .generators import SchemaGenerator
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/rest_framework/schemas/generators.py", line 11, in <module>
    from django.contrib.admindocs.views import simplify_regex
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/django/contrib/admindocs/views.py", line 7, in <module>
    from django.contrib import admin
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 4, in <module>
    from django.contrib.admin.filters import (
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 10, in <module>
    from django.contrib.admin.options import IncorrectLookupParameters
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 12, in <module>
    from django.contrib.admin import helpers, widgets
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized
```

**Comment by kryskool** [comment]
I close this PR, because, cause superseded by #1465

**Pull request closed without merging**
