### PR TITLE
Use asyncio from redis instead of aioredis to make app python 3.11 compatible

### PR DESCRIPTION
**Pull request by florealcab**
Description of the issue/feature this PR addresses:

Policyd part crash on debian 12

Current behavior before PR:

The policyd supervisor crash with a well known bug on aioredis with python 3.11. Like I found [here](https://github.com/aio-libs/aioredis-py/issues/1443), aioredis is not maintained anymore, but we can replace it by redis with asyncio (with redis >= 4.2.0rc1)

Desired behavior after PR is merged:

I made the change and all seems to work well with python 3.11, but we should want more testers!

### CODE REVIEW

**Comment by Spitfireap** [comment]
Hi, can you add 3.11 version to the github workflow ?

**Comment by florealcab** [comment]
Sure, I add it to the list of python versions in the workflow :)

**Comment by Spitfireap** [comment]
Thanks :). So looks like we need to update to account for the [deprecation](https://docs.python.org/3/whatsnew/3.11.html#removed). Can you look at it ? :D

**Comment by Spitfireap** [comment]
I would advise replacing the coroutine from asynctest with [this](https://docs.python.org/3/library/unittest.mock.html?highlight=asyncmock#unittest.mock.AsyncMock).

**Comment by florealcab** [comment]
Thank you, I use it now. The tests passed I hoped I have set it correctly because I never use it not asynctest before. if I make mistakes, don't hesitate to correct me :)

**Comment by Spitfireap** [comment]
Wonderful, seems good :)

**Pull request merged**
