### PR TITLE
Improve travis test with TOXENV

### PR DESCRIPTION
**Pull request by kryskool**
Description of the issue/feature this PR addresses:

Use TOXENV with travis

### CODE REVIEW

**Comment by tonioo** [comment]
@kryskool Looks like travis build has not been triggered?

**Comment by fyfe** [comment]
The travis.yml syntax is incorrect, TOXENV needs to be under env -> matrix (where DB used to be)

You'll also have issues with Python > 3.4 not being installed as Travis only installs the python version specified in the python setting (2.7 and 3.4 are installed by default in Debian)

**Comment by kryskool** [comment]
Hi @fyfe 

Your right, i rewrite the .travis.yml file. it works now

Regards,

**Comment by kryskool** [comment]
Hi @tonioo 

It's seem there is a problem with entities in Python 3 and SQLite
```
FAIL: test_map_upgrade (modoboa.admin.tests.test_mapfiles.MapFilesTestCase)
Check that map content is used.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/modoboa/modoboa/.tox/py35-dj111-sqlite/lib/python3.5/site-packages/modoboa/admin/tests/test_mapfiles.py", line 49, in test_map_upgrade
    self.assertEqual(mapcontent["dbpath"], dbsettings["NAME"])
AssertionError: 'file:memorydb_default?mode=memory&amp;cache=shared' != 'file:memorydb_default?mode=memory&cache=shared'
- file:memorydb_default?mode=memory&amp;cache=shared
?                                   ----
+ file:memorydb_default?mode=memory&cache=shared
```

Regards,

**Comment by kryskool** [comment]
@fyfe thnaks for the review

yes i prefer your solution, i change my code

> @kryskool the Django 2 builds are using Django 1.11.12
>https://travis-ci.org/modoboa/modoboa/jobs/366485787#L628

I must check the tox.ini file

Regards,

**Comment by kryskool** [comment]
I think we must protect `password` if containt HTML entities

**Comment by gawel** [comment]
Hi. In django-webtest I've created a py script to convert `tox -l` to a travis conf: https://github.com/django-webtest/django-webtest/blob/master/django_webtest_tests/tox2travis.py Maybe this can work for you too.

**Comment by tonioo** [comment]
@kryskool I guess we can close this PR. What do you think?

**Pull request closed without merging**
