### PR TITLE
Allow local addresses for forward definition.

### LINKED ISSUE #998: forward : Permission denied
hi

forwarding an account to a local destination isn't working, even when set as admin:
Permission denied: You can't define a forward to a local destination. Please ask your administrator to create an alias instead.

maybe i miss something?
there is
- account1@foo.bar
- account2@foo.bar

during holyday of account1 the emails should be forwarded to account2@foo.bar (with/without keeping local copy as account1 likes).
how to solve this?

thanks a lot

### PR DESCRIPTION
**Pull request by tonioo**
fix #998

### CODE REVIEW

**Comment by cmdtstof** [comment]
means implemente?
thanks
stof

**Comment by tonioo** [comment]
@cmdtstof yes, but only in the master branch. I will be released with the next modoboa version (1.7.0)

**Comment by cmdtstof** [comment]
then another €100 is on your way
and we try to start a
!!! crowdfunding for a modoboa auto update function !!!
thanks

**Comment by tonioo** [comment]
@cmdtstof Thank you!
Are you joking about the crowdfunding campaign ?

**Comment by cmdtstof** [comment]
@tonioo
not really. there is already a positive reaction for it! :-)
let's think about it via PM

**Pull request merged**
